# Generated by Django 3.2.10 on 2021-12-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('ReportId', models.AutoField(primary_key=True, serialize=False)),
                ('PlayerName', models.CharField(max_length=100)),
                ('PositionName', models.CharField(max_length=100)),
                ('TeamName', models.CharField(max_length=100)),
                ('OFV', models.IntegerField(default=0)),
                ('PlayerType', models.CharField(max_length=50)),
                ('HittingGrade', models.IntegerField()),
                ('HittingText', models.TextField(blank=True, null=True, verbose_name='Hitting Report')),
                ('PowerGrade', models.IntegerField()),
                ('PowerText', models.TextField(blank=True, null=True, verbose_name='Power Report')),
                ('RunningGrade', models.IntegerField()),
                ('RunningText', models.TextField(blank=True, null=True, verbose_name='Running Report')),
                ('FieldingGrade', models.IntegerField()),
                ('FieldingText', models.TextField(blank=True, null=True, verbose_name='Fielding Report')),
                ('ThrowingGrade', models.IntegerField()),
                ('ThrowingText', models.TextField(blank=True, null=True, verbose_name='Throwing Report')),
                ('FastballGrade', models.IntegerField()),
                ('FastballVelocity', models.IntegerField()),
                ('FastballText', models.TextField(blank=True, null=True, verbose_name='Fastball Report')),
                ('ChangeupGrade', models.IntegerField()),
                ('ChangeupVelocity', models.IntegerField()),
                ('ChangeupText', models.TextField(blank=True, null=True, verbose_name='Changeup Report')),
                ('SliderGrade', models.IntegerField()),
                ('SliderVelocity', models.IntegerField()),
                ('SliderText', models.TextField(blank=True, null=True, verbose_name='Slider Report')),
                ('CurveballGrade', models.IntegerField()),
                ('CurveballVelocity', models.IntegerField()),
                ('CurveballText', models.TextField(blank=True, null=True, verbose_name='Curveball Report')),
            ],
        ),
    ]
