# Generated by Django 3.2.10 on 2021-12-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='ChangeupGrade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='ChangeupVelocity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='CurveballGrade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='CurveballVelocity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='FastballGrade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='FastballVelocity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='FieldingGrade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='HittingGrade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='PowerGrade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='RunningGrade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='SliderGrade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='SliderVelocity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='ThrowingGrade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
