# Generated by Django 3.2.10 on 2021-12-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportApp', '0002_auto_20211213_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='ChangeupGrade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='ChangeupVelocity',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='CurveballGrade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='CurveballVelocity',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='FastballGrade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='FastballVelocity',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='FieldingGrade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='HittingGrade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='OFV',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='reports',
            name='PowerGrade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='RunningGrade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='SliderGrade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='SliderVelocity',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='ThrowingGrade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
